apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: devopsdozo
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "devops_learning"
  ALLOWED_ORIGINS: "*"
  APP_VERSION: "kind-local"