apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: devopsdozo
type: Opaque
stringData:
  DB_USERNAME: appuser
  DB_PASSWORD: changeme123
  DB_LINK: "postgresql://appuser:changeme123@postgres:5432/devops_learning"
  SECRET_KEY: "dev-secret-key"